name: Github Action for Java release
on:
  push:
    tags:
      - 'v*'
jobs:
  tag-release:
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      #  拉代码
      - uses: actions/checkout@v3
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      #  安装Jdk
      - name: Setup JDK 8
        id: setup_jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: maven
          server-id: sonatype
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      #  安装gpg证书
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      #  编译、发布jar到中央仓库
      - name: Publish package
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        run: mvn -B -Prelease -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} clean deploy
      - run: mkdir staging && cp target/*.jar staging
      #  发布版本
      - name: Set Tag Env
        id: set_tag_env
        run: echo tag_name=${GITHUB_REF#refs/*/} >> $GITHUB_ENV
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          title: Release ${{  env.tag_name }}
          files: |
            staging/*.jar
